# automatically generated by the FlatBuffers compiler, do not modify

# namespace: HttpInterceptor

class CoreMessageType(object):
    NONE = 0
    FilterModel = 1
    RuleModel = 2
    SyncMessage = 3


def CoreMessageTypeCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == CoreMessageType().FilterModel:
        import HttpInterceptor.FilterModel
        return HttpInterceptor.FilterModel.FilterModelT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == CoreMessageType().RuleModel:
        import HttpInterceptor.RuleModel
        return HttpInterceptor.RuleModel.RuleModelT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == CoreMessageType().SyncMessage:
        import HttpInterceptor.SyncMessage
        return HttpInterceptor.SyncMessage.SyncMessageT.InitFromBuf(table.Bytes, table.Pos)
    return None
