# automatically generated by the FlatBuffers compiler, do not modify

# namespace: HttpInterceptor

class Operator(object):
    CONTAINS = 0
    EQUALS = 1
    STARTS_WITH = 2
    ENDS_WITH = 3
    REGEX = 4

