# automatically generated by the FlatBuffers compiler, do not modify

# namespace: HttpInterceptor

class RuleAction(object):
    ADD_HEADER = 0
    MODIFY_HEADER = 1
    DELETE_HEADER = 2
    MODIFY_BODY = 3
    BLOCK_REQUEST = 4
    AUTO_RESPOND = 5

