// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { FlowData, FlowDataT } from '../http-interceptor/flow-data.js';
import { ServerEvent, ServerEventT } from '../http-interceptor/server-event.js';


export enum WebSocketMessageType {
  NONE = 0,
  ServerEvent = 1,
  FlowData = 2
}

export function unionToWebSocketMessageType(
  type: WebSocketMessageType,
  accessor: (obj:FlowData|ServerEvent) => FlowData|ServerEvent|null
): FlowData|ServerEvent|null {
  switch(WebSocketMessageType[type]) {
    case 'NONE': return null; 
    case 'ServerEvent': return accessor(new ServerEvent())! as ServerEvent;
    case 'FlowData': return accessor(new FlowData())! as FlowData;
    default: return null;
  }
}

export function unionListToWebSocketMessageType(
  type: WebSocketMessageType, 
  accessor: (index: number, obj:FlowData|ServerEvent) => FlowData|ServerEvent|null, 
  index: number
): FlowData|ServerEvent|null {
  switch(WebSocketMessageType[type]) {
    case 'NONE': return null; 
    case 'ServerEvent': return accessor(index, new ServerEvent())! as ServerEvent;
    case 'FlowData': return accessor(index, new FlowData())! as FlowData;
    default: return null;
  }
}
